workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.44.6
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
