// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBo0R4-CsuA9FqQpupqP1s61I_6gKCjI',
    appId: '1:340500256654:web:e13140d716b1b1423ff6df',
    messagingSenderId: '340500256654',
    projectId: 'sageosf-cf0dc',
    authDomain: 'sageosf-cf0dc.firebaseapp.com',
    storageBucket: 'sageosf-cf0dc.firebasestorage.app',
    measurementId: 'G-6Q2CC1KQ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilQu9CPXaP3MOkiutHH1N-sX8S8C9Mb0',
    appId: '1:340500256654:android:143d4123291275483ff6df',
    messagingSenderId: '340500256654',
    projectId: 'sageosf-cf0dc',
    storageBucket: 'sageosf-cf0dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqlnh161shwAxGwyEySnpFwjhBiSQRig',
    appId: '1:340500256654:ios:677e028bf9311cf53ff6df',
    messagingSenderId: '340500256654',
    projectId: 'sageosf-cf0dc',
    storageBucket: 'sageosf-cf0dc.firebasestorage.app',
    iosBundleId: 'com.sageos.sageMainframe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVqlnh161shwAxGwyEySnpFwjhBiSQRig',
    appId: '1:340500256654:ios:677e028bf9311cf53ff6df',
    messagingSenderId: '340500256654',
    projectId: 'sageosf-cf0dc',
    storageBucket: 'sageosf-cf0dc.firebasestorage.app',
    iosBundleId: 'com.sageos.sageMainframe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANBo0R4-CsuA9FqQpupqP1s61I_6gKCjI',
    appId: '1:340500256654:web:b24a40436ccf41203ff6df',
    messagingSenderId: '340500256654',
    projectId: 'sageosf-cf0dc',
    authDomain: 'sageosf-cf0dc.firebaseapp.com',
    storageBucket: 'sageosf-cf0dc.firebasestorage.app',
    measurementId: 'G-658YNQDRTH',
  );
}
